# Qasim Shahid
# SWE 645 Assignment 3
# This file defines a Kubernetes deployment for the SurveyAPI application.
# It specifies the number of replicas, the container image to use, and the ports to expose.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyapi-deployment
  labels:
    app: surveyapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyapi
  template:
    metadata:
      labels:
        app: surveyapi
    spec:
      containers:
      - name: surveyapi
        image: qshahid/surveyapi:latest # Ensure this matches your Docker image
        ports:
        - containerPort: 8080