apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyapi-deployment
  labels:
    app: surveyapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveyapi
  template:
    metadata:
      labels:
        app: surveyapi
    spec:
      containers:
      - name: surveyapi
        image: qshahid/surveyapi:latest # Ensure this matches your Docker image
        ports:
        - containerPort: 8080