apiVersion: v1
kind: Service
metadata:
  name: surveyapi-service
  labels:
    app: surveyapi
spec:
  type: NodePort
  ports:
  - port: 8080 # The port exposed by the service
    targetPort: 8080 # The port on the container
    nodePort: 30007 # Static port between 30000-32767
  selector:
    app: surveyapi